language: python
dist: xenial
services:
  - docker

#cache:
#  directories:
#  - $HOME/ScienceTools

notifications:
  email: false

python : 3.7

env:
    global:
      - SLAC_ST_BUILD=false
      - PIP_DEPS='coverage pytest-cov'
      - PYTHON_VERSION=3.7
      - INSTALL_CMD='python setup.py install'
      - CONDA_CHANNELS=conda-forge
      - CONDA_DOWNLOAD=Miniconda3-latest-Linux-x86_64.sh
      - CONDA_DEPS='gammapy numpy astropy scipy matplotlib pyyaml astropy-healpix'
      - CONDA2_DEPS='subprocess32 pytest'
      - FERMI_CONDA_CHANNELS='-c conda-forge/label/cf201901 -c fermi -c fermi/label/beta'
      - FERMIPY_CONDA_ENV='fermipy'
      - DOCKER_INSTALL=''
      
matrix:
    include:

        # The main build:
        # Python 3, lastest tag of fermitools, all dependencies
        - os: linux
          env: NAME=main
               PYTHON_VERSION=3.7
               ST_INSTALL="conda install -y --name $FERMIPY_CONDA_ENV -c conda-forge -c fermi -c fermi/label/beta fermitools=2.0.2"
 
        # The old build:
        # Python 3, fixed tag of fermitools, all dependencies
        - os: linux
          env: NAME=old
               ST_INSTALL="conda install -y --name $FERMIPY_CONDA_ENV -c conda-forge -c fermi -c fermi/label/beta fermitools=2.0.0"

        # Python 3.7, no Fermi ST, all other dependencies
        - os: linux
          env: NAME=no-deps
               ST_INSTALL='echo'
               CONDA2_DEPS='pytest'


    allow_failures:
        # The Sphinx docs build
        # Python 3, no Fermi ST, all other dependencies
        - os: linux
          env: NAME=docs
               ST_INSTALL='echo'
               PIP_DEPS='coverage pytest-cov coveralls'
               CONDA2_DEPS='pytest sphinx sphinx_rtd_theme'

#before_install:
#  - cat Dockerfile
#  - $DOCKER_SETUP
#  - ls

# Setup anaconda and install packages
install:
  # Download and install the ST binaries
  - if [[ $DOCKER_INSTALL == '' ]]; then
        source condainstall.sh;
    else
        $DOCKER_INSTALL;
        docker exec fermipy-testing /bin/bash --login -c "cd /home/fermipy && python setup.py install";
    fi

# Run test
script:
  - if [[ $DOCKER_INSTALL == '' ]]; then
        bash travistests.sh;
    else
        docker exec fermipy-testing /bin/bash --login -c "cd /home/fermipy;/bin/bash /home/fermipy/travistests.sh";
    fi

after_success:
  - if [[ $NAME == 'main' ]]; then
        coveralls --rcfile='fermipy/tests/coveragerc';
    elif [[ $SLAC_ST_BUILD == 'true' ]]; then
        docker exec fermipy-testing /bin/bash --login -c "cd /home/fermipy;source condasetup.sh;coveralls --rcfile='fermipy/tests/coveragerc'";
    fi

#after_script:
#    - if [[ $DOCKER_INSTALL != '' ]]; then
#          echo stopping docker;
#          docker stop test0;
#          docker rm test0;
#      fi
